### ISSUE TITLE
Would you accept a DC load class, even if not speced by IVI

### ISSUE THREAD

**Issue by OSHW-Rico** [gotmc/ivi#15]
As far as I can see DC loads are not covered by IVI.

Would you accept a PR anyways?

**Comment by matthewrankin** [comment]
Yes.

**Comment by matthewrankin** [comment]
Is there a particular model DC load that you were wanting to add?

**Comment by OSHW-Rico** [comment]
I would like to add something to control the SDL1000X series. I have already forked to add the Keysight E364xA psu model, since it is incompatible with the E36xx driver. Is is single channel only and has not the same feature set. I also found some bugs (or at least very suspicous things) in the E36xx driver. I try to find the time to upload a PR with all things I have added as soon as I know they work as intended.

**Comment by matthewrankin** [comment]
Closing this issue for now. Feel free to submit a pull request whenever you have something for a DC load.
